# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15if5WS64FnnGbN8HAaPqgIyD1obW1gm7
"""

import numpy as np
import pandas as pd

ea  = pd.read_csv("/content/drive/MyDrive/Visual Analytics CW/Dataset/Economic Activity.csv")

ea

# 2021 Tenure only covers England & Wales, so we align all 2011 datasets to the same geography.
def filter_eng_wales(df):
    mask = df["geography code"].str.startswith(("E", "W"))
    dropped = (~mask).sum()
    print(f"  Dropped {dropped} non-England/Wales rows")
    return df[mask].reset_index(drop=True)

print("Filtering Economic Activity:")
ea  = filter_eng_wales(ea)

# Economic Activity: select & rename relevant columns
df1_final = ea[[
    "geography",
    "geography code",
    "Economic Activity: All usual residents aged 16 to 74; measures: Value",
    "Economic Activity: Economically active: Unemployed; measures: Value",
    "Economic Activity: Economically inactive: Long-term sick or disabled; measures: Value",
]].rename(columns={
    "geography":                                                                              "area_name",
    "geography code":                                                                         "area_code",
    "Economic Activity: All usual residents aged 16 to 74; measures: Value":                 "total_residents_16_74",
    "Economic Activity: Economically active: Unemployed; measures: Value":                   "unemployed",
    "Economic Activity: Economically inactive: Long-term sick or disabled; measures: Value": "inactive_long_term_sick",
})

df1_final["unemployment_rate"]     = (df1_final["unemployed"]             / df1_final["total_residents_16_74"]).round(4)
df1_final["inactivity_sick_rate"]  = (df1_final["inactive_long_term_sick"]/ df1_final["total_residents_16_74"]).round(4)

print(df1_final.shape)
print(df1_final.head(3))

df1_final

df1_final = df1_final.drop(columns=['inactive_long_term_sick', 'inactivity_sick_rate'])
display(df1_final.head())

df1_final

df_2 = pd.read_csv("/content/drive/MyDrive/Visual Analytics CW/Dataset/Tenure.csv")

df_2

print("Filtering Tenure 2011:")
df_2 = filter_eng_wales(df_2)

# Tenure 2011: select & rename relevant columns
# Keep: total households (denominator), social rented, private rented
# These mirror the exact same columns in Tenure 2021, enabling direct
# year-on-year comparison for H3 (tenure shift 2011 → 2021)

df2_final = df_2[[
    "geography code",
    "Tenure: All households; measures: Value",
    "Tenure: Social rented; measures: Value",
    "Tenure: Private rented; measures: Value",
]].rename(columns={
    "geography code":                            "area_code",
    "Tenure: All households; measures: Value":   "total_households_2011",
    "Tenure: Social rented; measures: Value":    "social_rented_2011",
    "Tenure: Private rented; measures: Value":   "private_rented_2011",
})

df2_final["pct_social_rented_2011"]  = (df2_final["social_rented_2011"]  / df2_final["total_households_2011"]).round(4)
df2_final["pct_private_rented_2011"] = (df2_final["private_rented_2011"] / df2_final["total_households_2011"]).round(4)

print(df2_final.shape)
print(df2_final.head(3))

df2_final

df2_final = df2_final.drop(columns=['social_rented_2011', 'pct_social_rented_2011'])
display(df2_final.head())

df_3 = pd.read_csv("/content/drive/MyDrive/Visual Analytics CW/Dataset/Highest Level of Qualification.csv")

df_3

print("Filtering Qualification:")
df_3 = filter_eng_wales(df_3)

# Qualification: select & rename relevant columns
# Keep: total usual residents (denominator), no qualifications, level 4+
# The two extremes of the qualification spectrum — these form the axis
# for H1 and H2 (low-qual → high unemployment + high social renting)

df3_final = df_3[[
    "geography code",
    "Qualification: All categories: Highest level of qualification; measures: Value",
    "Qualification: No qualifications; measures: Value",
    "Qualification: Level 4 qualifications and above; measures: Value",
]].rename(columns={
    "geography code":                                                                    "area_code",
    "Qualification: All categories: Highest level of qualification; measures: Value":   "total_usual_residents",
    "Qualification: No qualifications; measures: Value":                                "no_qualifications",
    "Qualification: Level 4 qualifications and above; measures: Value":                 "level4_and_above",
})

df3_final["pct_no_quals"] = (df3_final["no_qualifications"] / df3_final["total_usual_residents"]).round(4)
df3_final["pct_level4"]   = (df3_final["level4_and_above"]  / df3_final["total_usual_residents"]).round(4)

print(df3_final.shape)
print(df3_final.head(3))

df3_final

# Merge all four datasets on area_code
# Inner join keeps only the 323 Local Authorities present in ALL datasets

Final_2011 = (
    df1_final
    .merge(df2_final, on="area_code", how="inner")
    .merge(df3_final,   on="area_code", how="inner")
)

print("Final_2011 shape:", Final_2011.shape)
print("Areas retained:", Final_2011["area_name"].nunique())

Final_2011

df_2021 = pd.read_csv("/content/drive/MyDrive/Visual Analytics CW/Dataset/Tenure 2021.csv")

df_2021

# Tenure 2021: select & rename relevant columns

df2021_final = df_2021[[
    "geography code",
    "Tenure of household: Total: All households",
    "Tenure of household: Social rented",
    "Tenure of household: Private rented",
]].rename(columns={
    "geography code":                               "area_code",
    "Tenure of household: Total: All households":   "total_households_2021",
    "Tenure of household: Social rented":           "social_rented_2021",
    "Tenure of household: Private rented":          "private_rented_2021",
})

df2021_final["pct_social_rented_2021"]  = (df2021_final["social_rented_2021"]  / df2021_final["total_households_2021"]).round(4)
df2021_final["pct_private_rented_2021"] = (df2021_final["private_rented_2021"] / df2021_final["total_households_2021"]).round(4)

print(df2021_final.shape)
print(df2021_final.head(3))

df2021_final

df2021_final = df2021_final.drop(columns=['social_rented_2021', 'pct_social_rented_2021'])
display(df2021_final.head())

# Merge all four datasets on area_code

Absolute_Dataset = (
    Final_2011
    .merge(df2021_final, on="area_code", how="inner")
)

print("Merge shape:", Absolute_Dataset.shape)
print("Areas retained:", Absolute_Dataset["area_name"].nunique())

Absolute_Dataset

#  Preview final column set
print("\nFinal columns:")
for col in Absolute_Dataset.columns:
    print(f"  {col}")

print("\nSample rows:")
print(Absolute_Dataset.head(5).to_string())

# Export
Absolute_Dataset.to_csv("census_merged_clean.csv", index=False)
print(f"\nSaved: census_merged_clean.csv — {Absolute_Dataset.shape[0]} rows × {Absolute_Dataset.shape[1]} columns")

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE

# No missing values in this dataset — imputation not needed

feature_cols = [
    "unemployment_rate",
    "pct_private_rented_2011",
    "pct_private_rented_2021",
    "pct_no_quals",
    "pct_level4",
]

X_raw = Absolute_Dataset[feature_cols].copy()
labels = Absolute_Dataset["area_name"]

print("Feature matrix shape:", X_raw.shape)
print("Missing values:", X_raw.isnull().sum().sum())  # should be 0

# No imputation needed — dataset is complete
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_raw)

print("Mean per feature (should be ~0):", X_scaled.mean(axis=0).round(4))
print("Std per feature  (should be ~1):", X_scaled.std(axis=0).round(4))

# Run PCA
pca = PCA(n_components=2, random_state=42)
X_pca = pca.fit_transform(X_scaled)

# Variance explained
var_explained = pca.explained_variance_ratio_
print(f"PC1 variance explained: {var_explained[0]*100:.2f}%")
print(f"PC2 variance explained: {var_explained[1]*100:.2f}%")
print(f"Total variance explained: {sum(var_explained)*100:.2f}%")

# Component loadings — tells you which features drive each PC
loadings = pd.DataFrame(
    pca.components_.T,
    index=feature_cols,
    columns=["PC1", "PC2"]
).round(4)
print("\nPCA Loadings:\n", loadings.to_string())

# Build result dataframe for export
pca_df = pd.DataFrame(X_pca, columns=["PC1", "PC2"])
pca_df.insert(0, "area_code", Absolute_Dataset["area_code"].values)
pca_df.insert(0, "area_name", Absolute_Dataset["area_name"].values)
pca_df["unemployment_rate"] = Absolute_Dataset["unemployment_rate"].values
pca_df["pct_private_rented_2021"] = Absolute_Dataset["pct_private_rented_2021"].values
pca_df["pct_level4"] = Absolute_Dataset["pct_level4"].values

fig, axes = plt.subplots(1, 2, figsize=(16, 7))
fig.suptitle("PCA — 2011 Census (England & Wales)", fontsize=14, fontweight="bold", y=1.01)

#  Left: coloured by unemployment rate
ax = axes[0]
sc = ax.scatter(
    pca_df["PC1"], pca_df["PC2"],
    c=pca_df["unemployment_rate"],
    cmap="RdYlGn_r",
    s=45, alpha=0.75, edgecolors="white", linewidths=0.4
)
plt.colorbar(sc, ax=ax, label="Unemployment rate")
ax.set_xlabel(f"PC1  ({var_explained[0]*100:.1f}% variance)", fontsize=11)
ax.set_ylabel(f"PC2  ({var_explained[1]*100:.1f}% variance)", fontsize=11)
ax.set_title("Coloured by unemployment rate", fontsize=11)
ax.axhline(0, color="grey", linewidth=0.5, linestyle="--")
ax.axvline(0, color="grey", linewidth=0.5, linestyle="--")

# Annotate the top 5 highest-unemployment outliers
top_outliers = pca_df.nlargest(5, "unemployment_rate")
for _, row in top_outliers.iterrows():
    ax.annotate(
        row["area_name"], xy=(row["PC1"], row["PC2"]),
        xytext=(5, 5), textcoords="offset points",
        fontsize=7, color="#555"
    )

# Right: loading biplot overlay
ax2 = axes[1]
sc2 = ax2.scatter(
    pca_df["PC1"], pca_df["PC2"],
    c=pca_df["pct_level4"],
    cmap="Blues",
    s=45, alpha=0.75, edgecolors="white", linewidths=0.4
)
plt.colorbar(sc2, ax=ax2, label="% Level 4+ qualifications")
ax2.set_xlabel(f"PC1  ({var_explained[0]*100:.1f}% variance)", fontsize=11)
ax2.set_ylabel(f"PC2  ({var_explained[1]*100:.1f}% variance)", fontsize=11)
ax2.set_title("Coloured by % Level 4+ quals — with loadings", fontsize=11)
ax2.axhline(0, color="grey", linewidth=0.5, linestyle="--")
ax2.axvline(0, color="grey", linewidth=0.5, linestyle="--")

# Draw loading arrows
scale = 2.5   # scale arrows to be visible relative to scatter
for feature, (pc1_load, pc2_load) in zip(feature_cols, pca.components_.T):
    ax2.annotate(
        "", xy=(pc1_load * scale, pc2_load * scale), xytext=(0, 0),
        arrowprops=dict(arrowstyle="->", color="#D85A30", lw=1.5)
    )
    ax2.text(
        pc1_load * scale * 1.12, pc2_load * scale * 1.12,
        feature, fontsize=7.5, color="#D85A30", ha="center"
    )

plt.tight_layout()
plt.savefig("pca_scatter.png", dpi=150, bbox_inches="tight")
plt.show()
print("Saved: pca_scatter.png")

# Run t-SNE
tsne = TSNE(
    n_components=2,
    perplexity=30,
    learning_rate="auto",
    n_iter=1000,
    init="pca",          # PCA init is more stable than random
    random_state=42
)
X_tsne = tsne.fit_transform(X_scaled)

print(f"t-SNE KL divergence (lower = better fit): {tsne.kl_divergence_:.4f}")

# Build result dataframe for export
tsne_df = pd.DataFrame(X_tsne, columns=["tSNE_1", "tSNE_2"])
tsne_df.insert(0, "area_code", Absolute_Dataset["area_code"].values)
tsne_df.insert(0, "area_name", Absolute_Dataset["area_name"].values)
tsne_df["unemployment_rate"]       = Absolute_Dataset["unemployment_rate"].values
tsne_df["pct_private_rented_2021"] = Absolute_Dataset["pct_private_rented_2021"].values
tsne_df["pct_level4"]              = Absolute_Dataset["pct_level4"].values
tsne_df["pct_no_quals"]            = Absolute_Dataset["pct_no_quals"].values

fig, axes = plt.subplots(1, 2, figsize=(16, 7))
fig.suptitle("t-SNE — 2011 Census (England & Wales)", fontsize=14, fontweight="bold", y=1.01)

# Left: coloured by % no qualifications
ax = axes[0]
sc = ax.scatter(
    tsne_df["tSNE_1"], tsne_df["tSNE_2"],
    c=tsne_df["pct_no_quals"],
    cmap="OrRd",
    s=45, alpha=0.8, edgecolors="white", linewidths=0.4
)
plt.colorbar(sc, ax=ax, label="% No qualifications")
ax.set_xlabel("t-SNE dimension 1", fontsize=11)
ax.set_ylabel("t-SNE dimension 2", fontsize=11)
ax.set_title("Coloured by % no qualifications", fontsize=11)

# Annotate top 5 highest no-quals areas
top5 = tsne_df.nlargest(5, "pct_no_quals")
for _, row in top5.iterrows():
    ax.annotate(
        row["area_name"], xy=(row["tSNE_1"], row["tSNE_2"]),
        xytext=(5, 5), textcoords="offset points",
        fontsize=7, color="#555"
    )

#  Right: coloured by % private renting 2021
ax2 = axes[1]
sc2 = ax2.scatter(
    tsne_df["tSNE_1"], tsne_df["tSNE_2"],
    c=tsne_df["pct_private_rented_2021"],
    cmap="PuBu",
    s=45, alpha=0.8, edgecolors="white", linewidths=0.4
)
plt.colorbar(sc2, ax=ax2, label="% Private rented (2021)")
ax2.set_xlabel("t-SNE dimension 1", fontsize=11)
ax2.set_ylabel("t-SNE dimension 2", fontsize=11)
ax2.set_title("Coloured by % private rented (2021)", fontsize=11)

# Annotate top 5 highest private renting areas
top5_pr = tsne_df.nlargest(5, "pct_private_rented_2021")
for _, row in top5_pr.iterrows():
    ax2.annotate(
        row["area_name"], xy=(row["tSNE_1"], row["tSNE_2"]),
        xytext=(5, 5), textcoords="offset points",
        fontsize=7, color="#555"
    )

plt.tight_layout()
plt.savefig("tsne_scatter.png", dpi=150, bbox_inches="tight")
plt.show()
print("Saved: tsne_scatter.png")

# Export PCA result
pca_df.to_csv("pca_result.csv", index=False)
print("Saved: pca_result.csv  →", pca_df.shape)

# Export t-SNE result
tsne_df.to_csv("tsne_result.csv", index=False)
print("Saved: tsne_result.csv →", tsne_df.shape)

# Export PCA loadings (useful for Tableau tooltip annotations)
loadings.reset_index().rename(columns={"index": "feature"}).to_csv(
    "pca_loadings.csv", index=False
)
print("Saved: pca_loadings.csv")

print("\nAll files ready for Tableau import.")

!pip install pymc --quiet

import matplotlib.gridspec as gridspec
import pymc as pm
import arviz as az
from scipy import stats

# Standardise predictors
from sklearn.preprocessing import StandardScaler

predictors = ["pct_private_rented_2011", "unemployment_rate", "pct_level4", "pct_no_quals"]
target     = "pct_private_rented_2021"

scaler = StandardScaler()
X = scaler.fit_transform(Absolute_Dataset[predictors])
y = Absolute_Dataset[target].values

with pm.Model() as bayes_reg_model:
    # Weakly informative priors
    alpha  = pm.Normal("alpha",  mu=y.mean(), sigma=0.05)
    beta   = pm.Normal("beta",   mu=0,        sigma=0.1,  shape=X.shape[1])
    sigma  = pm.HalfNormal("sigma", sigma=0.05)

    mu = alpha + pm.math.dot(X, beta)
    likelihood = pm.Normal("y_obs", mu=mu, sigma=sigma, observed=y)

    # Sample posterior
    trace_reg = pm.sample(2000, tune=1000, target_accept=0.9,
                          random_seed=42, progressbar=True)

az.summary(trace_reg, var_names=["alpha", "beta", "sigma"], round_to=4)

# Plot 1a: Posterior distributions of coefficients
fig, axes = plt.subplots(1, 4, figsize=(16, 4))
fig.suptitle("Bayesian Linear Regression — Posterior Distributions of Coefficients\n"
             "Predicting % Private Rented 2021", fontsize=12, fontweight="bold")

colors = ["#378ADD", "#E24B4A", "#1D9E75", "#EF9F27"]
beta_samples = trace_reg.posterior["beta"].values.reshape(-1, 4)

for i, (pred, color) in enumerate(zip(predictors, colors)):
    ax = axes[i]
    samples = beta_samples[:, i]
    ax.hist(samples, bins=50, color=color, alpha=0.75, edgecolor="white", linewidth=0.4)
    ax.axvline(samples.mean(), color="black", linewidth=1.5, linestyle="-",  label=f"Mean: {samples.mean():.4f}")
    ax.axvline(np.percentile(samples, 2.5),  color="black", linewidth=1,   linestyle="--", label="95% CI")
    ax.axvline(np.percentile(samples, 97.5), color="black", linewidth=1,   linestyle="--")
    ax.axvline(0, color="red", linewidth=0.8, linestyle=":", alpha=0.6)
    ax.set_title(pred.replace("pct_", "% "), fontsize=10)
    ax.set_xlabel("Coefficient value")
    ax.legend(fontsize=7)
    ax.set_ylabel("Frequency" if i == 0 else "")

plt.tight_layout()
plt.savefig("bayes_reg_posteriors.png", dpi=150, bbox_inches="tight")
plt.show()

# Plot 1b: Predicted vs Actual with 95% credible interval
with bayes_reg_model:
    ppc = pm.sample_posterior_predictive(trace_reg, random_seed=42)

y_pred_mean = ppc.posterior_predictive["y_obs"].mean(axis=(0, 1)).values
y_pred_lower = np.percentile(ppc.posterior_predictive["y_obs"].values.reshape(-1, len(y)), 2.5,  axis=0)
y_pred_upper = np.percentile(ppc.posterior_predictive["y_obs"].values.reshape(-1, len(y)), 97.5, axis=0)

sort_idx = np.argsort(y)
fig, ax = plt.subplots(figsize=(14, 5))
ax.scatter(range(len(y)), y[sort_idx], s=12, color="#2C2C2A", alpha=0.6,
           zorder=3, label="Observed")
ax.plot(range(len(y)), y_pred_mean[sort_idx], color="#378ADD",
        linewidth=1.5, label="Posterior mean")
ax.fill_between(range(len(y)), y_pred_lower[sort_idx], y_pred_upper[sort_idx],
                color="#378ADD", alpha=0.2, label="95% credible interval")
ax.set_xlabel("Local Authority (sorted by observed value)", fontsize=11)
ax.set_ylabel("% Private rented 2021", fontsize=11)
ax.set_title("Bayesian Linear Regression — Predicted vs Observed with 95% Credible Interval",
             fontsize=12, fontweight="bold")
ax.legend()
plt.tight_layout()
plt.savefig("bayes_reg_predicted_vs_actual.png", dpi=150, bbox_inches="tight")
plt.show()

# Step 1: Re-run posterior predictive to get per-area predictions
with bayes_reg_model:
    ppc = pm.sample_posterior_predictive(trace_reg, random_seed=42)

# Step 2: Extract per-area posterior predictive summaries
y_samples = ppc.posterior_predictive["y_obs"].values.reshape(-1, len(y))
# Shape: (n_samples, 323 areas)

per_area_df = pd.DataFrame({
    "area_name":                      Absolute_Dataset["area_name"].values,
    "area_code":                      Absolute_Dataset["area_code"].values,
    "pct_private_rented_2011":        Absolute_Dataset["pct_private_rented_2011"].values,
    "pct_private_rented_2021":        Absolute_Dataset["pct_private_rented_2021"].values,
    "unemployment_rate":              Absolute_Dataset["unemployment_rate"].values,
    "pct_level4":                     Absolute_Dataset["pct_level4"].values,
    "pct_no_quals":                   Absolute_Dataset["pct_no_quals"].values,

    # Posterior predictive for 2021 (fitted values with uncertainty)
    "predicted_2021_mean":            y_samples.mean(axis=0).round(4),
    "predicted_2021_lower":           np.percentile(y_samples, 2.5,  axis=0).round(4),
    "predicted_2021_upper":           np.percentile(y_samples, 97.5, axis=0).round(4),

    # Residual: observed minus predicted
    "residual":                       (Absolute_Dataset["pct_private_rented_2021"].values
                                       - y_samples.mean(axis=0)).round(4),
})

# Step 3: 2030 forecast
# Observed growth per area (2011 → 2021)
observed_growth = (Absolute_Dataset["pct_private_rented_2021"].values
                   - Absolute_Dataset["pct_private_rented_2011"].values)

with pm.Model() as forecast_model:
    mu_growth    = pm.Normal("mu_growth",    mu=0.03,  sigma=0.02)
    sigma_growth = pm.HalfNormal("sigma_growth", sigma=0.02)
    growth_obs   = pm.Normal("growth_obs", mu=mu_growth,
                             sigma=sigma_growth, observed=observed_growth)
    trace_forecast = pm.sample(2000, tune=1000, target_accept=0.9,
                               random_seed=42, progressbar=True)
    growth_2030    = pm.Normal("growth_2030", mu=mu_growth,
                               sigma=sigma_growth, shape=len(Absolute_Dataset))
    ppc_forecast   = pm.sample_posterior_predictive(
        trace_forecast, var_names=["growth_2030"], random_seed=42
    )

g2030_samples = ppc_forecast.posterior_predictive["growth_2030"].values.reshape(-1, len(Absolute_Dataset))
pred_2030     = Absolute_Dataset["pct_private_rented_2021"].values + g2030_samples

per_area_df["pct_private_rented_2030_mean"]  = pred_2030.mean(axis=0).round(4)
per_area_df["pct_private_rented_2030_lower"] = np.percentile(pred_2030, 2.5,  axis=0).round(4)
per_area_df["pct_private_rented_2030_upper"] = np.percentile(pred_2030, 97.5, axis=0).round(4)

# Step 4: Export
per_area_df.to_csv("bayesian_results.csv", index=False)
print("Saved: bayesian_results.csv —", per_area_df.shape)
print(per_area_df[["area_name", "pct_private_rented_2021",
                    "predicted_2021_mean", "pct_private_rented_2030_mean",
                    "pct_private_rented_2030_lower", "pct_private_rented_2030_upper"]].head(10).to_string())

# Step 5: Keep coefficient summary as a separate file (for your report)
coef_summary = az.summary(trace_reg, var_names=["alpha", "beta", "sigma"], round_to=4)
coef_summary.index = ["alpha"] + [f"beta_{p}" for p in predictors] + ["sigma"]
coef_summary.to_csv("bayes_coefficients.csv")
print("\nSaved: bayes_coefficients.csv (coefficient table for report)")

